services:
  db:
    image: postgres:${POSTGRES_VER}-bullseye
    environment:
      - POSTGRES_DB=${BUGHOUSE_DB_DATABASE}
      - POSTGRES_USER=${BUGHOUSE_DB_USER}
      - POSTGRES_PASSWORD=${BUGHOUSE_DB_PASSWORD}
      - POSTGRES_DB:${BUGHOUSE_DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - ${BUGHOUSE_DB_PORT}:${BUGHOUSE_DB_PORT}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "psql -h 127.0.0.1 -U $${POSTGRES_USER} -c select 1 -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data:rw
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        - NODE_VER=${NODE_VER}
    restart: always
    depends_on:
      db:
        condition: service_healthy
  gateway:
    build:
      context: docker/gateway
      args:
        - NGINX_VER=${NGINX_VER}
    ports:
      - 8080:80
    restart: always
    depends_on:
      - api
volumes:
  database:
